apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik-dashboard
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.global.ingressIP }}
    metallb.universe.tf/loadBalancerIPs: {{ .Values.global.ingressIP | quote }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: traefik
      port: {{ .Values.service.port }}
      targetPort: traefik
      protocol: TCP
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
{{- with .Values.service.additionalSpec }}
{{- toYaml . | nindent 2 }}
{{- end }}