service:
  type: ClusterIP
  port: 9000
  labels: {}
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.20"
  namespace: kube-system
  additionalSpec: {}

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "home-ca-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  host: traefik.home.lan
  issuer: home-ca-issuer
  tls: true
  tlsSecretName: tls-traefik-cert
