apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookstack-web
  name: bookstack-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bookstack-web
    spec:
      containers:
        - name: bookstack
          image: solidnerd/bookstack:26.5.1
          env:
            - name: APP_KEY
              valueFrom: 
                secretKeyRef:
                  name: {{ .Values.app.secret }}
                  key: app_key
            - name: APP_URL
              value: "https://{{ .Values.app.host }}"
            - name: APP_DEBUG
              value: "false"
            - name: APP_PROXIES
              value: "*"
            - name: DB_DATABASE
              value: bookstack
            - name: DB_HOST
              value: bookstack-mysql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.secret }} 
                  key: password
            - name: DB_USERNAME
              value: bookstack
            - name: AUTH_METHOD
              value: "oidc"
            - name: AUTH_AUTO_INITIATE
              value: "true"
            - name: OIDC_NAME
              value: "SSO"
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.secret }} 
                  key: client_id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.secret }} 
                  key: client_secret
            - name: OIDC_ISSUER
              value: "https://authentik.teegeedoubleyou.work/application/o/bookstack/"
            - name: OIDC_END_SESSION_ENDPOINT
              value: "true"
            - name: OIDC_ISSUER_DISCOVER
              value: "true"
            - name: OIDC_USER_TO_GROUPS
              value: "true"
            - name: OIDC_GROUPS_CLAIM
              value: "groups"
            - name: OIDC_REMOVE_FROM_GROUPS
              value: "true"
            - name: OIDC_ADDITIONAL_SCOPES
              value: "groups"

          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/bookstack/public/uploads
              name: uploads
            - mountPath: /var/www/bookstack/storage/uploads
              name: storage-uploads
      restartPolicy: Always
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: bookstack-uploads-pvc
        - name: storage-uploads
          persistentVolumeClaim:
            claimName: bookstack-storage-uploads-pvc
