apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookstack-mysql
  name: bookstack-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bookstack-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:9.2
          env:
            - name: MYSQL_DATABASE
              value: bookstack
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.secret }} 
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.secret }}
                  key: root_password
            - name: MYSQL_USER
              value: bookstack
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: bookstack-mysql-data
          ports:
            - containerPort: 3306
      restartPolicy: Always
      volumes:
        - name: bookstack-mysql-data
          persistentVolumeClaim:
            claimName: bookstack-mysql-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookstack-web
  name: bookstack-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bookstack-web
    spec:
      containers:
        - name: bookstack
          image: solidnerd/bookstack:25.5.2
          env:
            - name: APP_KEY
              valueFrom: 
                secretKeyRef:
                  name: {{ .Values.app.secret }}
                  key: app_key
            - name: APP_URL
              value: "https://{{ .Values.app.host }}"
            - name: APP_DEBUG
              value: "false"
            - name: APP_PROXIES
              value: "*"
            - name: DB_DATABASE
              value: bookstack
            - name: DB_HOST
              value: bookstack-mysql:3306
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.secret }} 
                  key: password
            - name: DB_USERNAME
              value: bookstack
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/bookstack/public/uploads
              name: uploads
            - mountPath: /var/www/bookstack/storage/uploads
              name: storage-uploads
      restartPolicy: Always
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: bookstack-uploads-pvc
        - name: storage-uploads
          persistentVolumeClaim:
            claimName: bookstack-storage-uploads-pvc
