apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bookstack-network-policy
spec:
  podSelector:
    matchLabels:
      app: bookstack-mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: bookstack-web
    ports:
    - protocol: TCP
      port: 3306
