apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: {{ .Values.global.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-storage-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.global.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: {{ .Values.global.storageClassName }}

