replicaCount: 1

annotations: {}

image:
  name: ghcr.io/cloudnative-pg/postgresql:18
  pullPolicy: IfNotPresent

storage:
  storageClass: longhorn
  size: 20Gi

bootstrap:
  database: appdb
  owner: appuser

service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/load-balancer-ips: 192.168.1.22

postgresql:
  pg_hba:
    - host all all 192.168.1.0/24 scram-sha-256
    - host all all 192.168.10.0/24 scram-sha-256
    - host all all 10.42.0.0/16 scram-sha-256
