# Global values that can be accessed by all subcharts
global:
  storageClassName: longhorn

# Common Pi-hole configuration, not used directly by Helm but holds anchors
pihole_common_config: &pihole-common
  enabled: true
  replicaCount: 1
  strategyType: Recreate
  serviceDhcp:
    enabled: false
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  persistentVolumeClaim:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: "1Gi"
    storageClass: "longhorn"
  admin:
    enabled: true
    existingSecret: "pihole-secret"
    passwordKey: "password"
  extraEnvVars:
    FTLCONF_dns_listeningMode: 'all'
    TZ: Asia/Singapore
    FTLCONF_dns_hosts: |
      192.168.2.3    homeassistant.local;
      192.168.1.20   scrypted.teegeedoubleyou.work;
      192.168.1.20   uptime-kuma.teegeedoubleyou.work;
      192.168.1.20   vault.teegeedoubleyou.work;
      192.168.1.20   headlamp.teegeedoubleyou.work;
      192.168.1.20   traefik.teegeedoubleyou.work;
      192.168.1.20   longhorn.teegeedoubleyou.work;
      192.168.1.20   pihole-1.teegeedoubleyou.work;
      192.168.1.20   pihole-2.teegeedoubleyou.work;
      192.168.1.20   proxmox.teegeedoubleyou.work;
      192.168.1.20   wireguard.teegeedoubleyou.work;
      192.168.1.20   homepage.teegeedoubleyou.work;
      192.168.1.20   bookstack.teegeedoubleyou.work;
      192.168.1.20   plex.teegeedoubleyou.work;
      192.168.1.20   synology.teegeedoubleyou.work;
      192.168.1.20   unifi.teegeedoubleyou.work;

  DNS1: "1.1.1.1"
  DNS2: "1.0.0.1"
  adlists:
    - https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
    - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.plus.txt
    - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/tif.medium.txt
  whitelist:
    - msmetrics.ws.sonos.com
  capabilities:
    add:
    - CHOWN
    - NET_BIND_SERVICE
    - NET_RAW
    - NET_ADMIN
    - SYS_NICE
    - SYS_TIME
  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
      - 127.0.0.1
      - 1.1.1.1

# Common service and ingress parts
pihole_service_common: &pihole-service-common
  type: LoadBalancer
  annotations:
    metallb.io/allow-shared-ip: pihole-svc

pihole_ingress_common: &pihole-ingress-common
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  path: /
  pathType: ImplementationSpecific

pihole-1:
  <<: *pihole-common
  serviceDns:
    <<: *pihole-service-common
    loadBalancerIP: 192.168.1.53
  serviceWeb:
    <<: *pihole-service-common
    loadBalancerIP: 192.168.1.53
  ingress:
    <<: *pihole-ingress-common
    hosts:
      - pihole-1.teegeedoubleyou.work
    tls:
     - secretName: pihole-1-tls-secret
       hosts:
         - pihole-1.teegeedoubleyou.work

pihole-2:
  <<: *pihole-common
  serviceDns:
    <<: *pihole-service-common
    loadBalancerIP: 192.168.1.54
  serviceWeb:
    <<: *pihole-service-common
    loadBalancerIP: 192.168.1.54
  ingress:
    <<: *pihole-ingress-common
    hosts:
      - pihole-2.teegeedoubleyou.work
    tls:
     - secretName: pihole-2-tls-secret
       hosts:
         - pihole-2.teegeedoubleyou.work
