global:
  domain: ""
  clusterIssuer: ""
  ingressClassName: ""

namespaceOverride: ""

ingress:
  enabled: true
  host: ""
  hostPrefix: longhorn
  tlsSecretName: longhorn-tls-secret
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure

backend:
  serviceName: longhorn-frontend 
  servicePort: 80

service:
  enabled: true
  port: 80
  targetPort: http
  type: ClusterIP