apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  ingress: "true"
  traefik: "true"
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    {{- tpl (toYaml .Values.config.bookmarks) . | nindent 4 }}
  services.yaml: |
    {{- tpl (toYaml .Values.config.services) . | nindent 4 }}
  widgets.yaml: |
    {{- toYaml .Values.config.widgets | nindent 4 }}