apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    gethomepage.dev/description: Dynamically Detected Homepage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: homepage.png
    gethomepage.dev/name: Homepage
    {{- if .Values.global.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.global.clusterIssuer | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host | default (printf "%s.%s" .Values.ingress.hostPrefix (required "global.domain is required" .Values.global.domain)) }}
    secretName: {{ .Values.ingress.tlsSecretName | default "homepage-tls-secret" }}
  ingressClassName: {{ .Values.global.ingressClassName | default .Values.ingress.ingressClassName | default "traefik" }}
  rules:
    - host: {{ .Values.ingress.host | default (printf "%s.%s" .Values.ingress.hostPrefix (required "global.domain is required" .Values.global.domain)) }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000