apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingressroute
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`argocd.teegeedoubleyou.work`)
    kind: Rule
    services:
    - name: argocd-server
      port: 80
      scheme: http
  tls:
    secretName: argocd-tls-secret
