replicaCount: 1

image:
  repository: pihole/pihole
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  seccompProfile:
    type: RuntimeDefault
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: LoadBalancer
  ports:
    - port: 53
      name: dns-udp
      protocol: UDP
    - port: 53
      name: dns-tcp
      protocol: TCP
    - port: 80
      name: http
      protocol: TCP
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.6.53

env:
  - name: TZ
    value: "America/Singapore"
  - name: FTLCONF_webserver_api_password
    valueFrom:
      secretKeyRef:
        name: pihole-secret
        key: webpassword

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
