replicaCount: 1

image:
  repository: pihole/pihole
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}


securityContext:
  capabilities:
    add:
    - CHOWN
    - NET_BIND_SERVICE
    - NET_RAW
    - NET_ADMIN
    - SYS_NICE
    - SYS_TIME

service:
  type: LoadBalancer
  ports:
    - port: 53
      name: dns-udp
      protocol: UDP
    - port: 53
      name: dns-tcp
      protocol: TCP
    - port: 80
      name: http
      protocol: TCP
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.53

ingress:
  enabled: true
  ingressClassName: traefik
  annotations: {}
  hosts:
    - host: pihole.home.lan
      paths: 
        - path: /
          pathType: Prefix
          backend:
            servicePort: 80

env:
  - name: TZ
    value: "America/Singapore"
  - name: FTLCONF_webserver_api_password
    valueFrom:
      secretKeyRef:
        name: pihole-secret
        key: pw

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 2000m
    memory: 2Gi

livenessProbe:
  exec:
    command:
      - nslookup
      - localhost
      - 127.0.0.1
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  exec:
    command:
      - nslookup
      - localhost
      - 127.0.0.1
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
