apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-pvc
  namespace: home
  labels:
    app: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: home
  labels:
    app: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:1
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: kuma-data
              mountPath: /app/data
      volumes:
        - name: kuma-data
          persistentVolumeClaim:
            claimName: kuma-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: home
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.6.30
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: uptime-kuma