{{- range $name, $config := .Values.proxies }}
{{- if $config.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-ui-backend
  namespace: {{ $.Values.namespaceOverride | default $.Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: {{ $config.portName }}
    port: {{ $config.port }}
    targetPort: {{ $config.port }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ $name }}-ui-backend
  namespace: {{ $.Values.namespaceOverride | default $.Release.Namespace }}
subsets:
- addresses:
  - ip: {{ $config.ip }}
  ports:
  - name: {{ $config.portName }}
    port: {{ $config.port }}
---
{{- end }}
{{- end }}
