apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  annotations: {}
spec:
  selector:
    app: longhorn-ui
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- if .Values.service.enabled }}
  type: {{ .Values.service.type }}
{{- end }}