apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.21
spec:
  selector:
    app: longhorn-ui
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer
