global:
  domain: ""
  clusterIssuer: ""
  ingressClassName: ""

namespaceOverride: ""

ingress:
  enabled: true
  host: ""
  hostPrefix: headlamp
  tlsSecretName: headlamp-tls-secret
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure

backend:
  serviceName: my-headlamp
  servicePort: 80