ingress:
  enabled: true
  host: headlamp.teegeedoubleyou.work
  tlsSecretName: headlamp-tls-secret
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure

backend:
  serviceName: my-headlamp
  servicePort: 80