apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-ingress
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: headlamp
    app.kubernetes.io/name: headlamp
  annotations:
    {{- if .Values.global.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.global.clusterIssuer | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host | default (printf "headlamp.%s" (required "global.domain is required" .Values.global.domain)) }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  ingressClassName: {{ .Values.global.ingressClassName | default "traefik" }}
  rules:
    - host: {{ .Values.ingress.host | default (printf "headlamp.%s" (required "global.domain is required" .Values.global.domain)) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.servicePort }}