replicaCount: 1

image:
  repository: koush/scrypted
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports:
    - port: 11080
      name: http
      protocol: TCP
    - port: 10443
      name: https
      protocol: TCP
  annotations: {}

env:
  - name: SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION
    value: "Bearer SET_THIS_TO_SOME_RANDOM_TEXT"
  - name: SCRYPTED_WEBHOOK_UPDATE
    value: http://localhost:8080/v1/update

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: scrypted.teegeedoubleyou.work
      paths:
        - path: /
          pathType: Prefix
          backend:
            servicePort: 11080
  tls:
   - secretName: scrypted-tls-secret
     hosts:
       - scrypted.teegeedoubleyou.work

resources:
  limits:
    cpu: 4000m
    memory: 6Gi
  requests:
    cpu: 2000m
    memory: 3Gi

livenessProbe: {}
readinessProbe: {}

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

nodeSelector:
  kubernetes.io/hostname: zack-node-01