apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrypted.fullname" . }}
  labels:
    {{- include "scrypted.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $.Values.service.ports }}
    - port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort : {{ .port }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "scrypted.selectorLabels" . | nindent 4 }}
