apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  annotations:
    {{- if .Values.global.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.global.clusterIssuer | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
   - hosts:
     - {{ .Values.ingress.host | default (printf "%s.%s" .Values.ingress.hostPrefix (required "global.domain is required" .Values.global.domain)) }}
     secretName: {{ .Values.ingress.tlsSecretName }}
  ingressClassName: {{ .Values.global.ingressClassName | default "traefik" }}
  rules:
    - host: {{ .Values.ingress.host | default (printf "%s.%s" .Values.ingress.hostPrefix (required "global.domain is required" .Values.global.domain)) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200