apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pihole-password
  namespace: home
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: pihole
  refreshAfter: 1h
  destination:
    create: true
    name: pihole-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-token
  namespace: cert-manager
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: cloudflare
  refreshAfter: 1h
  destination:
    create: true
    name: cloudflare-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bookstack-password
  namespace: home
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: bookstack
  refreshAfter: 1h
  destination:
    create: true
    name: bookstack-secret