apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pihole-password
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: pihole
  refreshAfter: 1h
  destination:
    create: true
    name: pihole-secret

